/* DockController.c generated by valac 0.20.1, the Vala compiler
 * generated from DockController.vala, do not modify */

/**/
/*  Copyright (C) 2011 Robert Dyer*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER (valawebkitsandbox_main_controller_get_type ())
#define VALAWEBKITSANDBOX_MAIN_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER, ValawebkitsandboxMainController))
#define VALAWEBKITSANDBOX_MAIN_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER, ValawebkitsandboxMainControllerClass))
#define VALAWEBKITSANDBOX_IS_MAIN_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER))
#define VALAWEBKITSANDBOX_IS_MAIN_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER))
#define VALAWEBKITSANDBOX_MAIN_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER, ValawebkitsandboxMainControllerClass))

typedef struct _ValawebkitsandboxMainController ValawebkitsandboxMainController;
typedef struct _ValawebkitsandboxMainControllerClass ValawebkitsandboxMainControllerClass;
typedef struct _ValawebkitsandboxMainControllerPrivate ValawebkitsandboxMainControllerPrivate;

#define VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW (valawebkitsandbox_widgets_dock_window_get_type ())
#define VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW, ValawebkitsandboxWidgetsDockWindow))
#define VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW, ValawebkitsandboxWidgetsDockWindowClass))
#define VALAWEBKITSANDBOX_WIDGETS_IS_DOCK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW))
#define VALAWEBKITSANDBOX_WIDGETS_IS_DOCK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW))
#define VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW, ValawebkitsandboxWidgetsDockWindowClass))

typedef struct _ValawebkitsandboxWidgetsDockWindow ValawebkitsandboxWidgetsDockWindow;
typedef struct _ValawebkitsandboxWidgetsDockWindowClass ValawebkitsandboxWidgetsDockWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ValawebkitsandboxMainController {
	GObject parent_instance;
	ValawebkitsandboxMainControllerPrivate * priv;
	ValawebkitsandboxWidgetsDockWindow* window;
};

struct _ValawebkitsandboxMainControllerClass {
	GObjectClass parent_class;
};


static gpointer valawebkitsandbox_main_controller_parent_class = NULL;

GType valawebkitsandbox_main_controller_get_type (void) G_GNUC_CONST;
GType valawebkitsandbox_widgets_dock_window_get_type (void) G_GNUC_CONST;
enum  {
	VALAWEBKITSANDBOX_MAIN_CONTROLLER_DUMMY_PROPERTY
};
ValawebkitsandboxMainController* valawebkitsandbox_main_controller_new (void);
ValawebkitsandboxMainController* valawebkitsandbox_main_controller_construct (GType object_type);
ValawebkitsandboxWidgetsDockWindow* valawebkitsandbox_widgets_dock_window_new (ValawebkitsandboxMainController* controller);
ValawebkitsandboxWidgetsDockWindow* valawebkitsandbox_widgets_dock_window_construct (GType object_type, ValawebkitsandboxMainController* controller);
static void valawebkitsandbox_main_controller_finalize (GObject* obj);


ValawebkitsandboxMainController* valawebkitsandbox_main_controller_construct (GType object_type) {
	ValawebkitsandboxMainController * self = NULL;
	ValawebkitsandboxWidgetsDockWindow* _tmp0_;
	ValawebkitsandboxWidgetsDockWindow* _tmp1_;
#line 31 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	self = (ValawebkitsandboxMainController*) g_object_new (object_type, NULL);
#line 33 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	_tmp0_ = valawebkitsandbox_widgets_dock_window_new (self);
#line 33 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	g_object_ref_sink (_tmp0_);
#line 33 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	_g_object_unref0 (self->window);
#line 33 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	self->window = _tmp0_;
#line 35 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	_tmp1_ = self->window;
#line 35 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp1_);
#line 31 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	return self;
#line 94 "DockController.c"
}


ValawebkitsandboxMainController* valawebkitsandbox_main_controller_new (void) {
#line 31 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	return valawebkitsandbox_main_controller_construct (VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER);
#line 101 "DockController.c"
}


static void valawebkitsandbox_main_controller_class_init (ValawebkitsandboxMainControllerClass * klass) {
#line 25 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	valawebkitsandbox_main_controller_parent_class = g_type_class_peek_parent (klass);
#line 25 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	G_OBJECT_CLASS (klass)->finalize = valawebkitsandbox_main_controller_finalize;
#line 110 "DockController.c"
}


static void valawebkitsandbox_main_controller_instance_init (ValawebkitsandboxMainController * self) {
}


static void valawebkitsandbox_main_controller_finalize (GObject* obj) {
	ValawebkitsandboxMainController * self;
#line 25 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER, ValawebkitsandboxMainController);
#line 29 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	_g_object_unref0 (self->window);
#line 25 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/DockController.vala"
	G_OBJECT_CLASS (valawebkitsandbox_main_controller_parent_class)->finalize (obj);
#line 126 "DockController.c"
}


/**
 * A controller class for managing a single dock.
 */
GType valawebkitsandbox_main_controller_get_type (void) {
	static volatile gsize valawebkitsandbox_main_controller_type_id__volatile = 0;
	if (g_once_init_enter (&valawebkitsandbox_main_controller_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValawebkitsandboxMainControllerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) valawebkitsandbox_main_controller_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValawebkitsandboxMainController), 0, (GInstanceInitFunc) valawebkitsandbox_main_controller_instance_init, NULL };
		GType valawebkitsandbox_main_controller_type_id;
		valawebkitsandbox_main_controller_type_id = g_type_register_static (G_TYPE_OBJECT, "ValawebkitsandboxMainController", &g_define_type_info, 0);
		g_once_init_leave (&valawebkitsandbox_main_controller_type_id__volatile, valawebkitsandbox_main_controller_type_id);
	}
	return valawebkitsandbox_main_controller_type_id__volatile;
}



