/* DockWindow.c generated by valac 0.20.1, the Vala compiler
 * generated from DockWindow.vala, do not modify */

/**/
/*  Copyright (C) 2011-2012 Robert Dyer, Michal Hruby, Rico Tzschichholz*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <webkit/webkit.h>
#include <gtk/gtk.h>


#define VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW (valawebkitsandbox_widgets_dock_window_get_type ())
#define VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW, ValawebkitsandboxWidgetsDockWindow))
#define VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW, ValawebkitsandboxWidgetsDockWindowClass))
#define VALAWEBKITSANDBOX_WIDGETS_IS_DOCK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW))
#define VALAWEBKITSANDBOX_WIDGETS_IS_DOCK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW))
#define VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW, ValawebkitsandboxWidgetsDockWindowClass))

typedef struct _ValawebkitsandboxWidgetsDockWindow ValawebkitsandboxWidgetsDockWindow;
typedef struct _ValawebkitsandboxWidgetsDockWindowClass ValawebkitsandboxWidgetsDockWindowClass;
typedef struct _ValawebkitsandboxWidgetsDockWindowPrivate ValawebkitsandboxWidgetsDockWindowPrivate;

#define VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER (valawebkitsandbox_main_controller_get_type ())
#define VALAWEBKITSANDBOX_MAIN_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER, ValawebkitsandboxMainController))
#define VALAWEBKITSANDBOX_MAIN_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER, ValawebkitsandboxMainControllerClass))
#define VALAWEBKITSANDBOX_IS_MAIN_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER))
#define VALAWEBKITSANDBOX_IS_MAIN_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER))
#define VALAWEBKITSANDBOX_MAIN_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER, ValawebkitsandboxMainControllerClass))

typedef struct _ValawebkitsandboxMainController ValawebkitsandboxMainController;
typedef struct _ValawebkitsandboxMainControllerClass ValawebkitsandboxMainControllerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ValawebkitsandboxWidgetsDockWindow {
	GtkWindow parent_instance;
	ValawebkitsandboxWidgetsDockWindowPrivate * priv;
};

struct _ValawebkitsandboxWidgetsDockWindowClass {
	GtkWindowClass parent_class;
};

struct _ValawebkitsandboxWidgetsDockWindowPrivate {
	ValawebkitsandboxMainController* _controller;
};


extern WebKitWebView* valawebkitsandbox_widgets_view;
WebKitWebView* valawebkitsandbox_widgets_view = NULL;
extern GtkScrolledWindow* valawebkitsandbox_widgets_scrolled;
GtkScrolledWindow* valawebkitsandbox_widgets_scrolled = NULL;
extern GtkBox* valawebkitsandbox_widgets_box;
GtkBox* valawebkitsandbox_widgets_box = NULL;
extern GtkButton* valawebkitsandbox_widgets_buttonRefresh;
GtkButton* valawebkitsandbox_widgets_buttonRefresh = NULL;
static gpointer valawebkitsandbox_widgets_dock_window_parent_class = NULL;

GType valawebkitsandbox_widgets_dock_window_get_type (void) G_GNUC_CONST;
GType valawebkitsandbox_main_controller_get_type (void) G_GNUC_CONST;
#define VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW, ValawebkitsandboxWidgetsDockWindowPrivate))
enum  {
	VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW_DUMMY_PROPERTY,
	VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW_CONTROLLER
};
ValawebkitsandboxWidgetsDockWindow* valawebkitsandbox_widgets_dock_window_new (ValawebkitsandboxMainController* controller);
ValawebkitsandboxWidgetsDockWindow* valawebkitsandbox_widgets_dock_window_construct (GType object_type, ValawebkitsandboxMainController* controller);
static ValawebkitsandboxMainController* valawebkitsandbox_widgets_dock_window_get_controller (ValawebkitsandboxWidgetsDockWindow* self);
static void valawebkitsandbox_widgets_dock_window_set_controller (ValawebkitsandboxWidgetsDockWindow* self, ValawebkitsandboxMainController* value);
static GObject * valawebkitsandbox_widgets_dock_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void valawebkitsandbox_widgets_dock_window_finalize (GObject* obj);
static void _vala_valawebkitsandbox_widgets_dock_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_valawebkitsandbox_widgets_dock_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
 * Creates a new dock window.
 */
ValawebkitsandboxWidgetsDockWindow* valawebkitsandbox_widgets_dock_window_construct (GType object_type, ValawebkitsandboxMainController* controller) {
	ValawebkitsandboxWidgetsDockWindow * self = NULL;
	ValawebkitsandboxMainController* _tmp0_;
#line 47 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	g_return_val_if_fail (controller != NULL, NULL);
#line 49 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp0_ = controller;
#line 49 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	self = (ValawebkitsandboxWidgetsDockWindow*) g_object_new (object_type, "controller", _tmp0_, "type", GTK_WINDOW_TOPLEVEL, NULL);
#line 47 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	return self;
#line 105 "DockWindow.c"
}


ValawebkitsandboxWidgetsDockWindow* valawebkitsandbox_widgets_dock_window_new (ValawebkitsandboxMainController* controller) {
#line 47 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	return valawebkitsandbox_widgets_dock_window_construct (VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW, controller);
#line 112 "DockWindow.c"
}


static ValawebkitsandboxMainController* valawebkitsandbox_widgets_dock_window_get_controller (ValawebkitsandboxWidgetsDockWindow* self) {
	ValawebkitsandboxMainController* result;
	ValawebkitsandboxMainController* _tmp0_;
#line 42 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 42 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp0_ = self->priv->_controller;
#line 42 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	result = _tmp0_;
#line 42 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	return result;
#line 127 "DockWindow.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 42 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	return self ? g_object_ref (self) : NULL;
#line 134 "DockWindow.c"
}


static void valawebkitsandbox_widgets_dock_window_set_controller (ValawebkitsandboxWidgetsDockWindow* self, ValawebkitsandboxMainController* value) {
	ValawebkitsandboxMainController* _tmp0_;
	ValawebkitsandboxMainController* _tmp1_;
#line 42 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	g_return_if_fail (self != NULL);
#line 42 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp0_ = value;
#line 42 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 42 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_g_object_unref0 (self->priv->_controller);
#line 42 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	self->priv->_controller = _tmp1_;
#line 42 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	g_object_notify ((GObject *) self, "controller");
#line 153 "DockWindow.c"
}


static GObject * valawebkitsandbox_widgets_dock_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ValawebkitsandboxWidgetsDockWindow * self;
	GtkBox* _tmp0_;
	WebKitWebView* _tmp1_;
	GtkButton* _tmp2_;
	GtkButton* _tmp3_;
	GtkScrolledWindow* _tmp4_;
	GtkScrolledWindow* _tmp5_;
	WebKitWebView* _tmp6_;
	GtkBox* _tmp7_;
	GtkButton* _tmp8_;
	GtkBox* _tmp9_;
	GtkScrolledWindow* _tmp10_;
	GtkBox* _tmp11_;
	WebKitWebView* _tmp12_;
#line 52 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	parent_class = G_OBJECT_CLASS (valawebkitsandbox_widgets_dock_window_parent_class);
#line 52 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 52 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW, ValawebkitsandboxWidgetsDockWindow);
#line 54 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp0_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 54 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	g_object_ref_sink (_tmp0_);
#line 54 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_g_object_unref0 (valawebkitsandbox_widgets_box);
#line 54 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	valawebkitsandbox_widgets_box = _tmp0_;
#line 55 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp1_ = (WebKitWebView*) webkit_web_view_new ();
#line 55 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	g_object_ref_sink (_tmp1_);
#line 55 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_g_object_unref0 (valawebkitsandbox_widgets_view);
#line 55 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	valawebkitsandbox_widgets_view = _tmp1_;
#line 56 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp2_ = (GtkButton*) gtk_button_new ();
#line 56 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	g_object_ref_sink (_tmp2_);
#line 56 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_g_object_unref0 (valawebkitsandbox_widgets_buttonRefresh);
#line 56 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	valawebkitsandbox_widgets_buttonRefresh = _tmp2_;
#line 57 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp3_ = valawebkitsandbox_widgets_buttonRefresh;
#line 57 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	gtk_button_set_label (_tmp3_, "Refresh");
#line 59 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp4_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 59 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	g_object_ref_sink (_tmp4_);
#line 59 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_g_object_unref0 (valawebkitsandbox_widgets_scrolled);
#line 59 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	valawebkitsandbox_widgets_scrolled = _tmp4_;
#line 60 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp5_ = valawebkitsandbox_widgets_scrolled;
#line 60 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp6_ = valawebkitsandbox_widgets_view;
#line 60 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	gtk_container_add ((GtkContainer*) _tmp5_, (GtkWidget*) _tmp6_);
#line 62 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp7_ = valawebkitsandbox_widgets_box;
#line 62 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp8_ = valawebkitsandbox_widgets_buttonRefresh;
#line 62 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	gtk_box_pack_start (_tmp7_, (GtkWidget*) _tmp8_, FALSE, FALSE, (guint) 0);
#line 63 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp9_ = valawebkitsandbox_widgets_box;
#line 63 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp10_ = valawebkitsandbox_widgets_scrolled;
#line 63 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	gtk_box_pack_start (_tmp9_, (GtkWidget*) _tmp10_, TRUE, TRUE, (guint) 0);
#line 64 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp11_ = valawebkitsandbox_widgets_box;
#line 64 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp11_);
#line 65 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_tmp12_ = valawebkitsandbox_widgets_view;
#line 65 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	webkit_web_view_load_uri (_tmp12_, "../data/web/test.html");
#line 67 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 68 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	gtk_window_resize ((GtkWindow*) self, 500, 500);
#line 52 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	return obj;
#line 248 "DockWindow.c"
}


static void valawebkitsandbox_widgets_dock_window_class_init (ValawebkitsandboxWidgetsDockWindowClass * klass) {
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	valawebkitsandbox_widgets_dock_window_parent_class = g_type_class_peek_parent (klass);
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	g_type_class_add_private (klass, sizeof (ValawebkitsandboxWidgetsDockWindowPrivate));
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_valawebkitsandbox_widgets_dock_window_get_property;
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_valawebkitsandbox_widgets_dock_window_set_property;
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	G_OBJECT_CLASS (klass)->constructor = valawebkitsandbox_widgets_dock_window_constructor;
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	G_OBJECT_CLASS (klass)->finalize = valawebkitsandbox_widgets_dock_window_finalize;
#line 265 "DockWindow.c"
	/**
	 * The controller for this dock.
	 */
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW_CONTROLLER, g_param_spec_object ("controller", "controller", "controller", VALAWEBKITSANDBOX_TYPE_MAIN_CONTROLLER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 271 "DockWindow.c"
}


static void valawebkitsandbox_widgets_dock_window_instance_init (ValawebkitsandboxWidgetsDockWindow * self) {
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	self->priv = VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW_GET_PRIVATE (self);
#line 278 "DockWindow.c"
}


static void valawebkitsandbox_widgets_dock_window_finalize (GObject* obj) {
	ValawebkitsandboxWidgetsDockWindow * self;
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW, ValawebkitsandboxWidgetsDockWindow);
#line 42 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	_g_object_unref0 (self->priv->_controller);
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	G_OBJECT_CLASS (valawebkitsandbox_widgets_dock_window_parent_class)->finalize (obj);
#line 290 "DockWindow.c"
}


/**
 * The main window for all docks.
 */
GType valawebkitsandbox_widgets_dock_window_get_type (void) {
	static volatile gsize valawebkitsandbox_widgets_dock_window_type_id__volatile = 0;
	if (g_once_init_enter (&valawebkitsandbox_widgets_dock_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValawebkitsandboxWidgetsDockWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) valawebkitsandbox_widgets_dock_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValawebkitsandboxWidgetsDockWindow), 0, (GInstanceInitFunc) valawebkitsandbox_widgets_dock_window_instance_init, NULL };
		GType valawebkitsandbox_widgets_dock_window_type_id;
		valawebkitsandbox_widgets_dock_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "ValawebkitsandboxWidgetsDockWindow", &g_define_type_info, 0);
		g_once_init_leave (&valawebkitsandbox_widgets_dock_window_type_id__volatile, valawebkitsandbox_widgets_dock_window_type_id);
	}
	return valawebkitsandbox_widgets_dock_window_type_id__volatile;
}


static void _vala_valawebkitsandbox_widgets_dock_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ValawebkitsandboxWidgetsDockWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW, ValawebkitsandboxWidgetsDockWindow);
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	switch (property_id) {
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
		case VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW_CONTROLLER:
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
		g_value_set_object (value, valawebkitsandbox_widgets_dock_window_get_controller (self));
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
		break;
#line 320 "DockWindow.c"
		default:
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
		break;
#line 326 "DockWindow.c"
	}
}


static void _vala_valawebkitsandbox_widgets_dock_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ValawebkitsandboxWidgetsDockWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALAWEBKITSANDBOX_WIDGETS_TYPE_DOCK_WINDOW, ValawebkitsandboxWidgetsDockWindow);
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
	switch (property_id) {
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
		case VALAWEBKITSANDBOX_WIDGETS_DOCK_WINDOW_CONTROLLER:
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
		valawebkitsandbox_widgets_dock_window_set_controller (self, g_value_get_object (value));
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
		break;
#line 342 "DockWindow.c"
		default:
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 36 "/home/gwen/Programmation/vala/vala-webkit-sandbox/lib/Widgets/DockWindow.vala"
		break;
#line 348 "DockWindow.c"
	}
}



